export const demoWorkouts = [
  {
    id: '1',
    date: '2026-05-19',
    category: 'Yoga',
    activityName: 'Morning Flow',
    durationMinutes: 60,
    intensity: 'Easy',
    notes: '',
  },
  {
    id: '2',
    date: '2026-05-19',
    category: 'Gym',
    activityName: 'Upper Body',
    durationMinutes: 45,
    intensity: 'Hard',
    notes: 'New PR on bench',
  },
  {
    id: '3',
    date: '2026-05-20',
    category: 'Hike',
    activityName: 'Tiger Mountain',
    durationMinutes: 90,
    intensity: 'Moderate',
    notes: '',
  },
  {
    id: '4',
    date: '2026-05-21',
    category: 'Swim',
    activityName: 'Lap Swim',
    durationMinutes: 30,
    intensity: 'Moderate',
    notes: '',
  },
  {
    id: '5',
    date: '2026-05-22',
    category: 'Gym',
    activityName: 'Leg Day',
    durationMinutes: 50,
    intensity: 'Hard',
    notes: '',
  },
  {
    id: '6',
    date: '2026-05-22',
    category: 'Yoga',
    activityName: 'Evening Stretch',
    durationMinutes: 30,
    intensity: 'Easy',
    notes: '',
  },
  {
    id: '7',
    date: '2026-05-13',
    category: 'Bike',
    activityName: 'Burke Gilman Trail',
    durationMinutes: 75,
    intensity: 'Moderate',
    notes: 'Great weather',
  },
  {
    id: '8',
    date: '2026-05-14',
    category: 'Gym',
    activityName: 'Push Day',
    durationMinutes: 45,
    intensity: 'Hard',
    notes: '',
  },
  {
    id: '9',
    date: '2026-05-15',
    category: 'Yoga',
    activityName: 'Hot Yoga',
    durationMinutes: 60,
    intensity: 'Moderate',
    notes: 'Core Power',
  },
  {
    id: '10',
    date: '2026-05-16',
    category: 'Hike',
    activityName: 'Rattlesnake Ridge',
    durationMinutes: 120,
    intensity: 'Hard',
    notes: 'Summit views!',
  },
  {
    id: '11',
    date: '2026-05-17',
    category: 'Swim',
    activityName: 'Open Water',
    durationMinutes: 45,
    intensity: 'Moderate',
    notes: '',
  },
  {
    id: '12',
    date: '2026-05-06',
    category: 'Gym',
    activityName: 'Full Body',
    durationMinutes: 60,
    intensity: 'Moderate',
    notes: '',
  },
  {
    id: '13',
    date: '2026-05-07',
    category: 'Bike',
    activityName: 'Spin Class',
    durationMinutes: 45,
    intensity: 'Hard',
    notes: '',
  },
  {
    id: '14',
    date: '2026-05-08',
    category: 'Yoga',
    activityName: 'Yin Yoga',
    durationMinutes: 75,
    intensity: 'Easy',
    notes: '',
  },
  {
    id: '15',
    date: '2026-05-10',
    category: 'Hike',
    activityName: 'Poo Poo Point',
    durationMinutes: 100,
    intensity: 'Moderate',
    notes: 'Paragliders!',
  },
];
